language: bash
services: docker

env:
 matrix:
  - PHP_VERSION=7.3 LIBXML_VERSION=2.9.9
  - PHP_VERSION=7.3 LIBXML_VERSION=2.9.8
  - PHP_VERSION=7.3 LIBXML_VERSION=2.9.7
  - PHP_VERSION=7.3 LIBXML_VERSION=2.9.6
  - PHP_VERSION=7.3 LIBXML_VERSION=2.9.5
  - PHP_VERSION=7.3 LIBXML_VERSION=2.9.4
  - PHP_VERSION=7.2 LIBXML_VERSION=2.9.9
  - PHP_VERSION=7.2 LIBXML_VERSION=2.9.8
  - PHP_VERSION=7.2 LIBXML_VERSION=2.9.7
  - PHP_VERSION=7.2 LIBXML_VERSION=2.9.6
  - PHP_VERSION=7.2 LIBXML_VERSION=2.9.5
  - PHP_VERSION=7.2 LIBXML_VERSION=2.9.4
  - PHP_VERSION=7.1 LIBXML_VERSION=2.9.9
  - PHP_VERSION=7.1 LIBXML_VERSION=2.9.8
  - PHP_VERSION=7.1 LIBXML_VERSION=2.9.7
  - PHP_VERSION=7.1 LIBXML_VERSION=2.9.6
  - PHP_VERSION=7.1 LIBXML_VERSION=2.9.5
  - PHP_VERSION=7.1 LIBXML_VERSION=2.9.4
  - PHP_VERSION=7.0 LIBXML_VERSION=2.9.9
  - PHP_VERSION=7.0 LIBXML_VERSION=2.9.8
  - PHP_VERSION=7.0 LIBXML_VERSION=2.9.7
  - PHP_VERSION=7.0 LIBXML_VERSION=2.9.6
  - PHP_VERSION=7.0 LIBXML_VERSION=2.9.5
  - PHP_VERSION=7.0 LIBXML_VERSION=2.9.4

install:
  - docker run --rm --volume $PWD:/app --workdir="/app" composer install

script:
  - docker build --build-arg php_version=${PHP_VERSION} --build-arg libxml_version=${LIBXML_VERSION} -t travis-build - < ./docker/php/Dockerfile
  - docker run --volume $PWD:/app --workdir="/app" travis-build php ./vendor/bin/phpunit --coverage-clover /app/test/clover.xml

after_script:
  - docker run --volume $PWD:/app --workdir="/app" composer require php-coveralls/php-coveralls:^2.0
  - docker run --volume $PWD:/app --workdir="/app" travis-build php ./vendor/php-coveralls/php-coveralls/bin/php-coveralls -v
